### ISSUE TITLE
giải thích

### ISSUE THREAD

**Issue by typicalsmc** [minhh2792/mcvn-optimization-guide#4]
thêm giải thích cho từng cái config như guide của youhavetrouble

**Comment by minhh2792** [comment]
no, in fact, i decided i dont care lolololololololol

**Comment by typicalsmc** [comment]
ok lol

Vào Th 6, 27 thg 8, 2021 vào lúc 22:13 minhh2792 ***@***.***>
đã viết:

**Comment by minhh2792** [comment]
test123 asdasd
