### ISSUE TITLE
Thêm giải thích và cảnh báo vào từng dòng config, để cho người đọc hiểu được những gì mình làm

### ISSUE THREAD

**Issue by TinLite** [minhh2792/mcvn-optimization-guide#5]
Như tiêu đề, thêm giải thích và cảnh báo vào từng dòng config, hoặc là gỡ đi những config nguy hiểm giống như [Server Optimization Guide](https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/) bên spigot.

Tác dụng: Người đọc sẽ hiểu được họ đang làm gì, impact đối với server ra sao, để không xảy ra hiện tượng một người làm server Survival [tắt nhầm thứ cần thiết](https://purpur.pl3x.net/docs/Configuration/#disable-treasure-searching) hay một người mới làm server, làm theo guide này và tải những plugin [vốn đã được server software họ sử dụng cung cấp](https://purpur.pl3x.net/docs/Configuration/#teleport-if-outside-border).

Cái guide này đang được recommend cho rất nhiều người, thậm chí cả tay mơ mới tập tành làm server, nên bật [thứ nguy hiểm có thể gây xung đột plugin](https://purpur.pl3x.net/docs/Configuration/#teleport-if-outside-border). Kịch bản đăng 7749 bài hỏi lỗi, cả đám đòi up cái folder plugins và mò từng plugin, rồi sau đó nhận ra là nó nằm trong config của server software trở thành một thứ hoàn toàn có thể xảy ra.

Nếu chưa có thời gian chỉnh sửa, hãy đặt 1 dòng notice bên trên cảnh báo mọi người, rằng cái guide này không nên được đọc và thực hiện bởi một người chưa tìm hiểu kĩ và không biết bình đang chỉnh cái gì.

**Comment by minhh2792** [comment]
updated, also check out this cute cat
https://www.youtube.com/watch?v=iik25wqIuFo

**Comment by TinLite** [comment]
I noticed that iik25 id, nice attemp. 👀

But how about the "description and warning" thing I mentioned above?

**Comment by minhh2792** [comment]
soon but not soon
Lazy af

**Comment by minhh2792** [comment]
ey yoo im horny wtf
đang chuyển sang gitbook để dễ maintain hơn, also yes
https://minhh2792.gitbook.io/toi-uu-server-minecraft/

**Comment by minhh2792** [comment]
Private me r
